services:
  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: agromind_pass
      DOCKER_INFLUXDB_INIT_ORG: agromind_org
      DOCKER_INFLUXDB_INIT_BUCKET: agromind_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: agromind_super_secret_token
    volumes:
      - influxdb_data:/var/lib/influxdb2

volumes:
  influxdb_data:
